# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Navigation
nav:
  - # - name:           "About"
    href:           "/about/"
  - # - name:           "RSS"
    href:           "/feed.xml"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Jered Benoit"
tagline: ""
description: "Follow <a href=\"https://micro.blog/jeredb\">@jeredb on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/jeredb\">@jeredb on Micro.blog</a>."
baseurl: ""
url: "https://jeredb.micro.blog"
markdown: "kramdown"
username: "jeredb"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Jered Benoit"
name: "Jered Benoit"
gravatar_hash: "6ab378c1f123f1a27fb1b584490c51b0"
avatar: "https://micro.blog/jeredb/avatar.jpg"
full_name: "Jered Benoit"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "538"